import { User, Lead, LeadNote, Followup, SystemSettings } from '../types';

export const INITIAL_USERS: User[] = [
  {
    id: 'u-admin-1',
    name: 'AeroPeak Admin',
    email: 'info@aeropeak.tech',
    phone: '+91 98765 00001',
    role: 'admin',
    status: 'active',
    password: 'AeroPeak@26',
    createdAt: '2026-01-15T09:00:00Z',
  },
  {
    id: 'u-dev-1',
    name: 'Devatharshini',
    email: 'devatharshini@gmail.com',
    phone: '+91 98765 00002',
    role: 'sales_rep',
    status: 'active',
    password: 'Deva@26',
    createdAt: '2026-02-01T10:30:00Z',
  },
  {
    id: 'u-3',
    name: 'Priya Sharma',
    email: 'priya.s@leadsquare.com',
    phone: '+91 98765 43210',
    role: 'sales_rep',
    status: 'active',
    createdAt: '2026-02-10T11:15:00Z',
  },
  {
    id: 'u-4',
    name: 'Michael Chen',
    email: 'michael.c@leadsquare.com',
    phone: '+1 800-555-0104',
    role: 'sales_rep',
    status: 'active',
    createdAt: '2026-03-05T14:20:00Z',
  },
];

export const INITIAL_LEADS: Lead[] = [
  {
    id: 'l-101',
    name: 'Robert Sterling',
    phone: '+1 415-555-2671',
    email: 'robert@apexindustries.com',
    company: 'Apex Tech Solutions',
    city: 'San Francisco',
    state: 'California',
    address: '100 Market St, Suite 400',
    remarks: 'Interested in enterprise cloud migration package.',
    assignedUserId: 'u-dev-1',
    assignedUserName: 'Devatharshini',
    status: 'interested',
    followupDate: '2026-08-05T10:00:00Z',
    createdAt: '2026-07-28T09:30:00Z',
    updatedAt: '2026-08-03T16:20:00Z',
  },
  {
    id: 'l-102',
    name: 'Ananya Gupta',
    phone: '+91 98765 43210',
    email: 'ananya@horizonventures.in',
    company: 'Horizon Ventures',
    city: 'Mumbai',
    state: 'Maharashtra',
    address: 'Bandra Kurla Complex, Tower B',
    remarks: 'Requested demo for team of 25 users.',
    assignedUserId: 'u-dev-1',
    assignedUserName: 'Devatharshini',
    status: 'follow_up',
    followupDate: '2026-08-04T15:30:00Z',
    createdAt: '2026-07-29T11:00:00Z',
    updatedAt: '2026-08-04T10:15:00Z',
  },
  {
    id: 'l-103',
    name: 'Carlos Mendez',
    phone: '+1 305-555-8821',
    email: 'cmendez@solarglobal.com',
    company: 'Global Solar Corp',
    city: 'Miami',
    state: 'Florida',
    address: '450 Brickell Ave',
    remarks: 'Signed annual subscription contract!',
    assignedUserId: 'u-dev-1',
    assignedUserName: 'Devatharshini',
    status: 'converted',
    followupDate: null,
    createdAt: '2026-07-20T14:00:00Z',
    updatedAt: '2026-08-02T11:30:00Z',
  },
  {
    id: 'l-104',
    name: 'Marcus Vance',
    phone: '+1 206-555-9012',
    email: 'marcus@vanceresearch.io',
    company: 'Vance Research Labs',
    city: 'Seattle',
    state: 'Washington',
    address: '720 5th Ave',
    remarks: 'Initial lead import from Tech Expo 2026.',
    assignedUserId: 'u-4',
    assignedUserName: 'Michael Chen',
    status: 'new',
    followupDate: '2026-08-06T11:00:00Z',
    createdAt: '2026-08-04T08:15:00Z',
    updatedAt: '2026-08-04T08:15:00Z',
  },
  {
    id: 'l-105',
    name: 'Emily Watson',
    phone: '+1 312-555-4433',
    email: 'ewatson@windycitylogistics.com',
    company: 'Windy City Logistics',
    city: 'Chicago',
    state: 'Illinois',
    address: '333 N Michigan Ave',
    remarks: 'Tried calling 3 times. Did not pick up.',
    assignedUserId: 'u-dev-1',
    assignedUserName: 'Devatharshini',
    status: 'dnp',
    followupDate: '2026-08-05T14:00:00Z',
    createdAt: '2026-07-30T13:40:00Z',
    updatedAt: '2026-08-03T09:10:00Z',
  },
  {
    id: 'l-106',
    name: 'Vikram Malhotra',
    phone: '+91 99887 76655',
    email: 'vikram@malhotratech.com',
    company: 'Malhotra Technologies',
    city: 'Bangalore',
    state: 'Karnataka',
    address: 'Indiranagar 100ft Road',
    remarks: 'Scheduled custom quotation review call.',
    assignedUserId: 'u-4',
    assignedUserName: 'Michael Chen',
    status: 'follow_up',
    followupDate: '2026-08-04T12:00:00Z',
    createdAt: '2026-08-01T10:00:00Z',
    updatedAt: '2026-08-04T09:00:00Z',
  },
  {
    id: 'l-107',
    name: 'Jessica Alba',
    phone: '+1 212-555-7788',
    email: 'jessica@manhattancreative.com',
    company: 'Manhattan Creative Studio',
    city: 'New York',
    state: 'New York',
    address: '500 Fifth Ave',
    remarks: 'Unassigned imported lead from website signups.',
    assignedUserId: null,
    assignedUserName: undefined,
    status: 'new',
    followupDate: null,
    createdAt: '2026-08-04T07:30:00Z',
    updatedAt: '2026-08-04T07:30:00Z',
  },
];

export const INITIAL_NOTES: LeadNote[] = [
  {
    id: 'n-1',
    leadId: 'l-101',
    userId: 'u-dev-1',
    userName: 'Devatharshini',
    note: 'Spoke with Robert. He is evaluating cloud platforms for 500+ employees. Sent product brochure and price breakdown.',
    statusAtTime: 'contacted',
    createdAt: '2026-07-30T11:00:00Z',
  },
  {
    id: 'n-2',
    leadId: 'l-101',
    userId: 'u-dev-1',
    userName: 'Devatharshini',
    note: 'Followed up after proposal. Robert confirmed high interest in the Enterprise Plan.',
    statusAtTime: 'interested',
    createdAt: '2026-08-03T16:20:00Z',
  },
  {
    id: 'n-3',
    leadId: 'l-102',
    userId: 'u-dev-1',
    userName: 'Devatharshini',
    note: 'Ananya requested a live demo with her technical lead tomorrow afternoon.',
    statusAtTime: 'follow_up',
    createdAt: '2026-08-04T10:15:00Z',
  },
  {
    id: 'n-4',
    leadId: 'l-103',
    userId: 'u-dev-1',
    userName: 'Devatharshini',
    note: 'Contract signed! Payment received via wire transfer.',
    statusAtTime: 'converted',
    createdAt: '2026-08-02T11:30:00Z',
  },
];

export const INITIAL_FOLLOWUPS: Followup[] = [
  {
    id: 'f-1',
    leadId: 'l-102',
    leadName: 'Ananya Gupta',
    leadPhone: '+91 98765 43210',
    leadCompany: 'Horizon Ventures',
    assignedUserId: 'u-dev-1',
    assignedUserName: 'Devatharshini',
    scheduledAt: '2026-08-04T15:30:00Z',
    notes: 'Technical product demo with team lead.',
    status: 'pending',
    createdAt: '2026-08-04T10:15:00Z',
  },
  {
    id: 'f-2',
    leadId: 'l-106',
    leadName: 'Vikram Malhotra',
    leadPhone: '+91 99887 76655',
    leadCompany: 'Malhotra Technologies',
    assignedUserId: 'u-4',
    assignedUserName: 'Michael Chen',
    scheduledAt: '2026-08-04T12:00:00Z',
    notes: 'Custom quotation review call.',
    status: 'overdue',
    createdAt: '2026-08-04T09:00:00Z',
  },
  {
    id: 'f-3',
    leadId: 'l-101',
    leadName: 'Robert Sterling',
    leadPhone: '+1 415-555-2671',
    leadCompany: 'Apex Tech Solutions',
    assignedUserId: 'u-dev-1',
    assignedUserName: 'Devatharshini',
    scheduledAt: '2026-08-05T10:00:00Z',
    notes: 'Final decision meeting regarding cloud package.',
    status: 'pending',
    createdAt: '2026-08-03T16:20:00Z',
  },
];

export const DEFAULT_SETTINGS: SystemSettings = {
  companyName: 'LeadSquare CRM',
  supportEmail: 'info@aeropeak.tech',
  currency: 'USD ($)',
  autoDistributionEnabled: true,
  duplicateCheckPhone: true,
  defaultFollowupDays: 3,
  leadStatuses: [
    { key: 'new', label: 'New Lead', color: 'bg-blue-50 text-blue-700 border-blue-200' },
    { key: 'contacted', label: 'Contacted', color: 'bg-cyan-50 text-cyan-700 border-cyan-200' },
    { key: 'follow_up', label: 'Follow Up Scheduled', color: 'bg-amber-50 text-amber-700 border-amber-200' },
    { key: 'interested', label: 'Interested', color: 'bg-emerald-50 text-emerald-700 border-emerald-200' },
    { key: 'not_interested', label: 'Not Interested', color: 'bg-rose-50 text-rose-700 border-rose-200' },
    { key: 'dnp', label: 'DNP (Did Not Pick)', color: 'bg-purple-50 text-purple-700 border-purple-200' },
    { key: 'busy', label: 'Busy / Callback', color: 'bg-orange-50 text-orange-700 border-orange-200' },
    { key: 'invalid_number', label: 'Invalid Number', color: 'bg-slate-100 text-slate-700 border-slate-200' },
    { key: 'converted', label: 'Converted', color: 'bg-green-50 text-green-700 border-green-200' },
  ],
};
